# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  git_url = "git@github.com:givtnl/givt.apps.codesigning.git"
  lane :certificates do
    match(type: "appstore", app_identifier: "nl.emag23.scanner", git_url: git_url)
  end

  desc "Push a new build to Testflight"
  lane :release do
    if git_branch == "main"
      app_identifier = "nl.emag23.scanner"
      flavor = "production"
    else
      app_identifier = "nl.emag23.scanner.beta"
      flavor = "development"
    end
    setup_ci
    sync_code_signing(type: "appstore", readonly: true, app_identifier: app_identifier, git_url: git_url)
    api_key = app_store_connect_api_key(
        key_id: "KAJ62HWFNH",
        issuer_id: "69a6de8f-dee3-47e3-e053-5b8c7c11a4d1",
        key_content: ENV['APPSTORECONNECT_PRIVATE_KEY']
    )
    build_number = latest_testflight_build_number(api_key: api_key, app_identifier: app_identifier) + 1
    Dir.chdir "../.." do
        sh("flutter", "packages", "get")
        sh("flutter", "clean")
        sh("flutter", "build", "ipa", "--flavor", flavor, "--target", "lib/main_#{flavor}.dart", "--build-number=#{build_number}")
    end
    build_app(
      scheme: flavor, 
      skip_build_archive: true, 
      include_symbols: true, 
      archive_path: "../build/ios/archive/Runner.xcarchive"
    )
    # set_github_release(
    #   repository_name: "lxh7/emag-scanner",
    #   api_token: ENV['GITHUB_API_TOKEN'], 
    #   name: "ios.ipa",
    #   tag_name: flutter_version(should_omit_version_code: true)["version_name"],
    #   upload_assets:[lane_context[SharedValues::IPA_OUTPUT_PATH]]
    # )
    dsym_zip
    upload_to_testflight(
      app_identifier: app_identifier,
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
