# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Generate keystore"
  lane :keystore do
    match_keystore(git_url: "git@github.com:givtnl/givt.apps.codesigning.git", package_name: "nl.emag23.scanner", override_keystore: true)
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Deploy a new version to the Google Play"
  lane :build_and_deploy do
    if git_branch == "main"
      package_name = "nl.emag23.scanner"
      flavor = "production"
    else
      package_name = "nl.emag23.scanner.beta"
      flavor = "development"
    end
    build_number = google_play_track_version_codes(package_name: package_name, track: "internal", json_key_data: ENV['GOOGLE_PLAY_JSON_KEY_DATA'])[0] + 1
    Dir.chdir "../.." do
        sh("flutter", "packages", "get")
        sh("flutter", "clean")
        sh("flutter", "build", "appbundle", "--flavor", flavor, "--target", "lib/main_#{flavor}.dart", "--build-number=#{build_number}")
    end
    signed_aab_path = match_keystore(git_url: "git@github.com:givtnl/givt.apps.codesigning.git", 
                    package_name: "nl.emag23.scanner.beta",
                    aab_path: "../build/app/outputs/bundle/#{flavor}Release/app-#{flavor}-release.aab",
                    match_secret: ENV['MATCH_PASSWORD'],
                    override_keystore: false)
    upload_to_play_store(package_name: package_name,
                        json_key_data: ENV['GOOGLE_PLAY_JSON_KEY_DATA'], 
                        aab: signed_aab_path,
                        release_status: "completed",
                        track: "internal")
  end
end
