name: Build and sign iOS
on: 
  push: 
    branches: [ production, main ]
jobs:
  build-ios: 
    name: Build Flutter iOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.118.0
        with: 
          ruby-version: '3.0'
          bundler-cache: true
      - name: Auth codesigning
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.CODESIGNING_DEPLOY_KEY }}
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Run Fastlane
        uses: maierj/fastlane-action@v2.3.0
        with:
          lane: ios release
          subdirectory: ios
        env: 
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          APPSTORECONNECT_PRIVATE_KEY: ${{ secrets.APPSTORECONNECT_PRIVATE_KEY }}
          GITHUB_API_TOKEN: ${{ secrets.PERSONAL_ACCESS_KEY }}
